version: 1.0.{build}
install:
- cmd: >-
    curl -fsSL -o dotnet-dev-win-x64.latest.zip 'https://dotnetcli.blob.core.windows.net/dotnet/beta/Binaries/Latest/dotnet-dev-win-x64.latest.zip'
    
    endlocal
    
    7z x dotnet-dev-win-x64.latest.zip -aoa -oC:\projects\lahda-compiler\
build_script:
- cmd: >-
    cd C:\projects\lahda-compiler\src\Lahda\

    dotnet restore
    
    dotnet build

test_script:
- cmd: >-
    cd C:\projects\EmployeeApp\test\Lahda.Tests\
    
    dotnet restore

    dotnet test