namespace Lahda
{
    public enum OperatorType
    {
        None,
        BitwiseOr,
        OrElse,
        BitwiseAnd,
        AndAlso,
        Add,
        Sub,
        Mul,
        Div,
        Mod,
        ParentheseOpen,
        ParentheseClose,
        BraceOpen,
        BraceClose,
        BracketOpen,
        BracketClose,
        Pow,
        Equals,
        NotEquals,
        Greater,
        Less,
        NotLess,
        NotGreater,
        Negate,
        Assign,
        AddAssign,
        SubAssign,
        MulAssign,
        DivAssign,
        ModAssign,
        Increment,
        Decrement,
        Comma
    }
}